### ISSUE TITLE
Undefined method `extension_whitelist'

### ISSUE THREAD

**Issue by jocubeit** [jonhue/avatari#2]
I'm trying to set the avatar of a user in a seed file (as per the instructions at carrierwave's github readme):

```
File.open(Rails.root.join('app', 'assets', 'images', 'Jurgen.png')) do |f|
  user.avatar = f
end

user.save!
```

I'm getting the following error:

```
NoMethodError: undefined method `extension_whitelist' for nil:NilClass
/app/vendor/bundle/ruby/2.4.0/gems/avatari-2.0.1/app/uploaders/avatari/avatar_uploader.rb:11:in `extension_whitelist'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/extension_whitelist.rb:40:in `check_extension_whitelist!'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/callbacks.rb:14:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/uploader/cache.rb:137:in `cache!'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/mounter.rb:44:in `block in cache'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/mounter.rb:42:in `map'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/mounter.rb:42:in `cache'
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/mount.rb:146:in `avatar='
/app/vendor/bundle/ruby/2.4.0/gems/carrierwave-1.2.2/lib/carrierwave/orm/activerecord.rb:70:in `avatar='
```

Using Rails 5.2.0.beta2.

Also, I found I had to add the carrierwave gem in my Gemfile before the avatari gem because of an uninitialized constant error, similar to #2.

**Comment by jonhue** [comment]
@JurgenJocubeit 

Can you verify that you added `avatari` to your `User` model?

Running `User.avatari_instance.extension_whitelist` works as expected in my app. https://github.com/jonhue/avatari/blob/master/app/uploaders/avatari/avatar_uploader.rb#L11

**Comment by jocubeit** [comment]
Yes definitely.

```ruby
  avatari colors: ['#1e87f0'],
    versions: {
      mini: [24,24], tiny: [50,50], small: [75,75], medium: [100,100], big: [350,350], raw: [500,500]
    },
    default_version: :tiny,
    process: [500,500],
    extension_whitelist: ['jpg','jpeg','png']
```

I even manually included the `Avatari::Model` concern to see if that would make a difference, but it didn't.

**Comment by jonhue** [comment]
@JurgenJocubeit

Could you try the following in your Rails console?

```ruby
User.avatari_instance.extension_whitelist
```
